/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package TCC.POO.SistemaMacDONALDS;

/**
 *
 * @author Gazebo
 */
public class PersonalizacaoCheeseburger extends javax.swing.JFrame {

    /**
     * Creates new form PersonalizacaoBigMac
     */
    public PersonalizacaoCheeseburger() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        checkPrado = new javax.swing.JCheckBox();
        checkBemPassado = new javax.swing.JCheckBox();
        checkAoPonto = new javax.swing.JCheckBox();
        checkMalPassado = new javax.swing.JCheckBox();
        checkKetchup = new javax.swing.JCheckBox();
        checkMostarda = new javax.swing.JCheckBox();
        checkMaionese = new javax.swing.JCheckBox();
        checkCebola = new javax.swing.JCheckBox();
        checkPicles = new javax.swing.JCheckBox();
        checkGergilim = new javax.swing.JCheckBox();
        checkCheddar = new javax.swing.JCheckBox();
        checkMussarela = new javax.swing.JCheckBox();
        btnEnviar = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        btnVoltar = new javax.swing.JButton();
        lblPreco = new javax.swing.JLabel();
        lblPreço = new javax.swing.JLabel();
        lblErroCampos = new javax.swing.JLabel();
        lblErroNome = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(775, 500));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Impact", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("PERSONALIZE SEU LANCHE");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(250, 20, 370, 40);

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Gazebo\\Documents\\NetBeansProjects\\TCC POO Sistema Mac Donalds\\MacLancheFeliz.png")); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(-50, 70, 420, 190);

        jLabel3.setFont(new java.awt.Font("Impact", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 0, 0));
        jLabel3.setText("Queijo:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(420, 380, 100, 14);

        jLabel4.setFont(new java.awt.Font("Impact", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 0, 0));
        jLabel4.setText("Ponto da carne:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(420, 140, 100, 14);

        jLabel5.setFont(new java.awt.Font("Impact", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 0, 0));
        jLabel5.setText("Molhos:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(420, 220, 100, 14);

        jLabel6.setFont(new java.awt.Font("Impact", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 0, 0));
        jLabel6.setText("Adicionais:");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(420, 310, 100, 14);

        checkPrado.setBackground(new java.awt.Color(255, 204, 0));
        checkPrado.setText("Prado");
        checkPrado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkPradoActionPerformed(evt);
            }
        });
        getContentPane().add(checkPrado);
        checkPrado.setBounds(640, 370, 110, 23);

        checkBemPassado.setBackground(new java.awt.Color(255, 204, 0));
        checkBemPassado.setText("Bem Passado");
        checkBemPassado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkBemPassadoActionPerformed(evt);
            }
        });
        getContentPane().add(checkBemPassado);
        checkBemPassado.setBounds(530, 120, 110, 23);

        checkAoPonto.setBackground(new java.awt.Color(255, 204, 0));
        checkAoPonto.setText("Ao Ponto");
        checkAoPonto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkAoPontoActionPerformed(evt);
            }
        });
        getContentPane().add(checkAoPonto);
        checkAoPonto.setBounds(530, 160, 110, 23);

        checkMalPassado.setBackground(new java.awt.Color(255, 204, 0));
        checkMalPassado.setText("Mal Passado");
        checkMalPassado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkMalPassadoActionPerformed(evt);
            }
        });
        getContentPane().add(checkMalPassado);
        checkMalPassado.setBounds(640, 120, 110, 23);

        checkKetchup.setBackground(new java.awt.Color(255, 204, 0));
        checkKetchup.setSelected(true);
        checkKetchup.setText("Ketchup");
        checkKetchup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkKetchupActionPerformed(evt);
            }
        });
        getContentPane().add(checkKetchup);
        checkKetchup.setBounds(530, 240, 110, 23);

        checkMostarda.setBackground(new java.awt.Color(255, 204, 0));
        checkMostarda.setSelected(true);
        checkMostarda.setText("Mostarda");
        checkMostarda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkMostardaActionPerformed(evt);
            }
        });
        getContentPane().add(checkMostarda);
        checkMostarda.setBounds(640, 200, 110, 23);

        checkMaionese.setBackground(new java.awt.Color(255, 204, 0));
        checkMaionese.setText("Maionese");
        checkMaionese.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkMaioneseActionPerformed(evt);
            }
        });
        getContentPane().add(checkMaionese);
        checkMaionese.setBounds(530, 200, 110, 23);

        checkCebola.setBackground(new java.awt.Color(255, 204, 0));
        checkCebola.setSelected(true);
        checkCebola.setText("Cebola");
        checkCebola.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkCebolaActionPerformed(evt);
            }
        });
        getContentPane().add(checkCebola);
        checkCebola.setBounds(530, 290, 110, 23);

        checkPicles.setBackground(new java.awt.Color(255, 204, 0));
        checkPicles.setSelected(true);
        checkPicles.setText("Picles");
        checkPicles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkPiclesActionPerformed(evt);
            }
        });
        getContentPane().add(checkPicles);
        checkPicles.setBounds(530, 320, 110, 23);

        checkGergilim.setBackground(new java.awt.Color(255, 204, 0));
        checkGergilim.setText("Gergilim");
        checkGergilim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkGergilimActionPerformed(evt);
            }
        });
        getContentPane().add(checkGergilim);
        checkGergilim.setBounds(640, 290, 110, 23);

        checkCheddar.setBackground(new java.awt.Color(255, 204, 0));
        checkCheddar.setSelected(true);
        checkCheddar.setText("Cheddar");
        checkCheddar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkCheddarActionPerformed(evt);
            }
        });
        getContentPane().add(checkCheddar);
        checkCheddar.setBounds(530, 370, 110, 23);

        checkMussarela.setBackground(new java.awt.Color(255, 204, 0));
        checkMussarela.setText("Mussarela");
        checkMussarela.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkMussarelaActionPerformed(evt);
            }
        });
        getContentPane().add(checkMussarela);
        checkMussarela.setBounds(530, 420, 110, 23);

        btnEnviar.setFont(new java.awt.Font("Impact", 0, 36)); // NOI18N
        btnEnviar.setForeground(new java.awt.Color(255, 0, 0));
        btnEnviar.setText("Enviar Pedido");
        btnEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnviarActionPerformed(evt);
            }
        });
        getContentPane().add(btnEnviar);
        btnEnviar.setBounds(150, 400, 250, 53);

        jLabel7.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 0, 0));
        jLabel7.setText("Digite seu nome:");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(20, 310, 130, 20);

        txtNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeActionPerformed(evt);
            }
        });
        getContentPane().add(txtNome);
        txtNome.setBounds(150, 300, 190, 30);

        btnVoltar.setText("VOLTAR");
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });
        getContentPane().add(btnVoltar);
        btnVoltar.setBounds(70, 20, 90, 23);

        lblPreco.setFont(new java.awt.Font("Impact", 0, 36)); // NOI18N
        lblPreco.setForeground(new java.awt.Color(255, 0, 0));
        lblPreco.setText("R$");
        getContentPane().add(lblPreco);
        lblPreco.setBounds(20, 410, 50, 45);

        lblPreço.setFont(new java.awt.Font("Impact", 0, 36)); // NOI18N
        lblPreço.setForeground(new java.awt.Color(255, 0, 0));
        lblPreço.setText("12");
        getContentPane().add(lblPreço);
        lblPreço.setBounds(80, 410, 50, 40);

        lblErroCampos.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        lblErroCampos.setForeground(new java.awt.Color(255, 0, 0));
        getContentPane().add(lblErroCampos);
        lblErroCampos.setBounds(430, 70, 360, 30);

        lblErroNome.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        lblErroNome.setForeground(new java.awt.Color(255, 0, 0));
        getContentPane().add(lblErroNome);
        lblErroNome.setBounds(110, 350, 260, 40);

        jLabel8.setIcon(new javax.swing.ImageIcon("C:\\Users\\Gazebo\\Documents\\NetBeansProjects\\TCC POO Sistema Mac Donalds\\Background.png")); // NOI18N
        jLabel8.setMaximumSize(new java.awt.Dimension(500, 500));
        getContentPane().add(jLabel8);
        jLabel8.setBounds(0, 160, 260, 160);

        jLabel9.setIcon(new javax.swing.ImageIcon("C:\\Users\\Gazebo\\Documents\\NetBeansProjects\\TCC POO Sistema Mac Donalds\\Background.png")); // NOI18N
        jLabel9.setMaximumSize(new java.awt.Dimension(500, 500));
        getContentPane().add(jLabel9);
        jLabel9.setBounds(0, 0, 260, 160);

        jLabel10.setIcon(new javax.swing.ImageIcon("C:\\Users\\Gazebo\\Documents\\NetBeansProjects\\TCC POO Sistema Mac Donalds\\Background.png")); // NOI18N
        jLabel10.setMaximumSize(new java.awt.Dimension(500, 500));
        getContentPane().add(jLabel10);
        jLabel10.setBounds(260, 320, 260, 160);

        jLabel11.setIcon(new javax.swing.ImageIcon("C:\\Users\\Gazebo\\Documents\\NetBeansProjects\\TCC POO Sistema Mac Donalds\\Background.png")); // NOI18N
        jLabel11.setMaximumSize(new java.awt.Dimension(500, 500));
        getContentPane().add(jLabel11);
        jLabel11.setBounds(260, 160, 260, 160);

        jLabel12.setIcon(new javax.swing.ImageIcon("C:\\Users\\Gazebo\\Documents\\NetBeansProjects\\TCC POO Sistema Mac Donalds\\Background.png")); // NOI18N
        jLabel12.setMaximumSize(new java.awt.Dimension(500, 500));
        getContentPane().add(jLabel12);
        jLabel12.setBounds(260, 0, 260, 160);

        jLabel13.setIcon(new javax.swing.ImageIcon("C:\\Users\\Gazebo\\Documents\\NetBeansProjects\\TCC POO Sistema Mac Donalds\\Background.png")); // NOI18N
        jLabel13.setMaximumSize(new java.awt.Dimension(500, 500));
        getContentPane().add(jLabel13);
        jLabel13.setBounds(520, 0, 260, 160);

        jLabel14.setIcon(new javax.swing.ImageIcon("C:\\Users\\Gazebo\\Documents\\NetBeansProjects\\TCC POO Sistema Mac Donalds\\Background.png")); // NOI18N
        jLabel14.setMaximumSize(new java.awt.Dimension(500, 500));
        getContentPane().add(jLabel14);
        jLabel14.setBounds(520, 160, 260, 160);

        jLabel15.setIcon(new javax.swing.ImageIcon("C:\\Users\\Gazebo\\Documents\\NetBeansProjects\\TCC POO Sistema Mac Donalds\\Background.png")); // NOI18N
        jLabel15.setMaximumSize(new java.awt.Dimension(500, 500));
        getContentPane().add(jLabel15);
        jLabel15.setBounds(520, 320, 260, 160);

        jLabel16.setIcon(new javax.swing.ImageIcon("C:\\Users\\Gazebo\\Documents\\NetBeansProjects\\TCC POO Sistema Mac Donalds\\Background.png")); // NOI18N
        jLabel16.setMaximumSize(new java.awt.Dimension(500, 500));
        getContentPane().add(jLabel16);
        jLabel16.setBounds(0, 320, 260, 160);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void checkPradoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkPradoActionPerformed
        // TODO add your handling code here:
        checkMussarela.setSelected(false);
        checkCheddar.setSelected(false);
    }//GEN-LAST:event_checkPradoActionPerformed

    private void checkAoPontoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkAoPontoActionPerformed
        // TODO add your handling code here:
        checkMalPassado.setSelected(false);
        checkBemPassado.setSelected(false);
    }//GEN-LAST:event_checkAoPontoActionPerformed

    private void checkMalPassadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkMalPassadoActionPerformed
        // TODO add your handling code here:
        checkBemPassado.setSelected(false);
        checkAoPonto.setSelected(false);
    }//GEN-LAST:event_checkMalPassadoActionPerformed

    private void checkKetchupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkKetchupActionPerformed
        // TODO add your handling code here:
         int preço = Integer.parseInt(lblPreço.getText());
        
        if(checkKetchup.isSelected()){
            preço = preço +  2;
        }else{
            preço = preço -  2;
        }
        lblPreço.setText(Integer.toString(preço));
    }//GEN-LAST:event_checkKetchupActionPerformed

    private void checkMostardaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkMostardaActionPerformed
        // TODO add your handling code here:
                int preço = Integer.parseInt(lblPreço.getText());
        
        if(checkMostarda.isSelected()){
            preço = preço +  2;
        }else{
            preço = preço -  2;
        }
        lblPreço.setText(Integer.toString(preço));
    }//GEN-LAST:event_checkMostardaActionPerformed

    private void checkMaioneseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkMaioneseActionPerformed
        // TODO add your handling code here:
        int preço = Integer.parseInt(lblPreço.getText());
        
        if(checkMaionese.isSelected()){
            preço = preço +  2;
        }else{
            preço = preço -  2;
        }
        lblPreço.setText(Integer.toString(preço));
    }//GEN-LAST:event_checkMaioneseActionPerformed

    private void checkCebolaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkCebolaActionPerformed
        // TODO add your handling code here:
         int preço = Integer.parseInt(lblPreço.getText());
        
        if(checkCebola.isSelected()){
            preço = preço +  2;
        }else{
            preço = preço -  2;
        }
        lblPreço.setText(Integer.toString(preço));
    }//GEN-LAST:event_checkCebolaActionPerformed

    private void checkPiclesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkPiclesActionPerformed
        // TODO add your handling code here:
         int preço = Integer.parseInt(lblPreço.getText());
        
        if(checkPicles.isSelected()){
            preço = preço +  2;
        }else{
            preço = preço -  2;
        }
        lblPreço.setText(Integer.toString(preço));
    }//GEN-LAST:event_checkPiclesActionPerformed

    private void checkGergilimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkGergilimActionPerformed
        // TODO add your handling code here:
         int preço = Integer.parseInt(lblPreço.getText());
        
        if(checkGergilim.isSelected()){
            preço = preço +  2;
        }else{
            preço = preço -  2;
        }
        lblPreço.setText(Integer.toString(preço));
    }//GEN-LAST:event_checkGergilimActionPerformed

    private void checkCheddarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkCheddarActionPerformed
        // TODO add your handling code here:
         checkMussarela.setSelected(false);
         checkPrado.setSelected(false);
    }//GEN-LAST:event_checkCheddarActionPerformed

    private void checkMussarelaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkMussarelaActionPerformed
        // TODO add your handling code here:
        checkCheddar.setSelected(false);
        checkPrado.setSelected(false);
    }//GEN-LAST:event_checkMussarelaActionPerformed

    private void txtNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeActionPerformed

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        // TODO add your handling code here:
        dispose();
        new TelaInicial().setVisible(true);
    }//GEN-LAST:event_btnVoltarActionPerformed

    private void checkBemPassadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkBemPassadoActionPerformed
        // TODO add your handling code here:
        checkMalPassado.setSelected(false);
        checkAoPonto.setSelected(false);
    }//GEN-LAST:event_checkBemPassadoActionPerformed

    private void btnEnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnviarActionPerformed
        // TODO add your handling code here:
        String carne = null;
            boolean ketchup= false;
            boolean MolhoEspecial= false;
            String Queijo = null;
            boolean picles= false;
            boolean cebola= false;
            boolean Mostarda= false;
            boolean gergilim=false;
            String cliente;

            if(checkBemPassado.isSelected()){
                carne = "Bem passado";
            }else if(checkMalPassado.isSelected()){
                carne = "Mal passado";
            }else if(checkAoPonto.isSelected()){
                carne = "Ao ponto";
            }

            if(checkKetchup.isSelected()){
                ketchup = true;
            }

            if(checkPicles.isSelected()){
                picles = true;
            }

            if(checkCebola.isSelected()){
                cebola = true;
            }

            if(checkMostarda.isSelected()){
                Mostarda = true;
            }

            if(checkGergilim.isSelected()){
                gergilim = true;
            }

            if(checkCheddar.isSelected()){
                Queijo = "Cheddar";
            }else if(checkMussarela.isSelected()){
                Queijo = "Mussarela";
            }else if(checkPrado.isSelected()){
                Queijo = "Prado";
            }
            
            if(carne == null || Queijo == null){
               lblErroCampos.setText("Os campos Carne e Queijo sao obrigatórios");
               return;
            }else{
                lblErroCampos.setText(" ");
            }
           
             int preco = Integer.parseInt(lblPreço.getText());
            cliente = txtNome.getText();
            System.out.println(cliente);
            if(cliente.isEmpty()){
                lblErroNome.setText("Digite seu nome para ser chamado");
                return;
            }else{
                lblErroNome.setText(" ");
            }

            Lanche lanche = new Lanche("Cheeseburger", carne, ketchup, MolhoEspecial, Queijo, picles, cebola, Mostarda, gergilim);
            Pedido pedido = new Pedido(lanche, cliente, preco);
            pedido.FazerPedido();
            lblErroNome.setText("PEDIDO ENVIADO");
    }//GEN-LAST:event_btnEnviarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PersonalizacaoCheeseburger.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PersonalizacaoCheeseburger.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PersonalizacaoCheeseburger.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PersonalizacaoCheeseburger.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PersonalizacaoCheeseburger().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEnviar;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JCheckBox checkAoPonto;
    private javax.swing.JCheckBox checkBemPassado;
    private javax.swing.JCheckBox checkCebola;
    private javax.swing.JCheckBox checkCheddar;
    private javax.swing.JCheckBox checkGergilim;
    private javax.swing.JCheckBox checkKetchup;
    private javax.swing.JCheckBox checkMaionese;
    private javax.swing.JCheckBox checkMalPassado;
    private javax.swing.JCheckBox checkMostarda;
    private javax.swing.JCheckBox checkMussarela;
    private javax.swing.JCheckBox checkPicles;
    private javax.swing.JCheckBox checkPrado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lblErroCampos;
    private javax.swing.JLabel lblErroNome;
    private javax.swing.JLabel lblPreco;
    private javax.swing.JLabel lblPreço;
    private javax.swing.JTextField txtNome;
    // End of variables declaration//GEN-END:variables
}
