/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package TCC.POO.SistemaMacDONALDS;

/**
 *
 * @author Gazebo
 */
public class TelaInicial extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public TelaInicial() {
        initComponents();
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnBigMac = new javax.swing.JButton();
        btnCheeseburger = new javax.swing.JButton();
        btnQuarteirao = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SISTEMA MAC DONALDS");
        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(775, 500));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Impact", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("ESCOLHA SEU LANCHE");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(190, 10, 360, 70);

        btnBigMac.setIcon(new javax.swing.ImageIcon("C:\\Users\\Gazebo\\Documents\\NetBeansProjects\\TCC POO Sistema Mac Donalds\\BigMac.png")); // NOI18N
        btnBigMac.setText("BIG MAC");
        btnBigMac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBigMacActionPerformed(evt);
            }
        });
        getContentPane().add(btnBigMac);
        btnBigMac.setBounds(10, 140, 220, 190);

        btnCheeseburger.setIcon(new javax.swing.ImageIcon("C:\\Users\\Gazebo\\Documents\\NetBeansProjects\\TCC POO Sistema Mac Donalds\\MacLancheFeliz.png")); // NOI18N
        btnCheeseburger.setText("Mac Lanche Feliz");
        btnCheeseburger.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCheeseburgerActionPerformed(evt);
            }
        });
        getContentPane().add(btnCheeseburger);
        btnCheeseburger.setBounds(250, 140, 240, 190);

        btnQuarteirao.setIcon(new javax.swing.ImageIcon("C:\\Users\\Gazebo\\Documents\\NetBeansProjects\\TCC POO Sistema Mac Donalds\\Quarteirao.jpg")); // NOI18N
        btnQuarteirao.setText("Quarteirao");
        btnQuarteirao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuarteiraoActionPerformed(evt);
            }
        });
        getContentPane().add(btnQuarteirao);
        btnQuarteirao.setBounds(520, 130, 220, 200);

        jLabel2.setFont(new java.awt.Font("Impact", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 0, 0));
        jLabel2.setText("Quarteirao");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(580, 360, 110, 31);

        jLabel3.setFont(new java.awt.Font("Impact", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 0, 0));
        jLabel3.setText("Big Mac");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(70, 360, 90, 31);

        jLabel4.setFont(new java.awt.Font("Impact", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 0, 0));
        jLabel4.setText("Cheeseburger");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(300, 360, 140, 31);

        jLabel5.setIcon(new javax.swing.ImageIcon("C:\\Users\\Gazebo\\Documents\\NetBeansProjects\\TCC POO Sistema Mac Donalds\\Background.png")); // NOI18N
        jLabel5.setMaximumSize(new java.awt.Dimension(500, 500));
        getContentPane().add(jLabel5);
        jLabel5.setBounds(0, 320, 260, 160);

        jLabel6.setIcon(new javax.swing.ImageIcon("C:\\Users\\Gazebo\\Documents\\NetBeansProjects\\TCC POO Sistema Mac Donalds\\Background.png")); // NOI18N
        jLabel6.setMaximumSize(new java.awt.Dimension(500, 500));
        getContentPane().add(jLabel6);
        jLabel6.setBounds(0, 0, 260, 160);

        jLabel7.setIcon(new javax.swing.ImageIcon("C:\\Users\\Gazebo\\Documents\\NetBeansProjects\\TCC POO Sistema Mac Donalds\\Background.png")); // NOI18N
        jLabel7.setMaximumSize(new java.awt.Dimension(500, 500));
        getContentPane().add(jLabel7);
        jLabel7.setBounds(260, 0, 260, 160);

        jLabel8.setIcon(new javax.swing.ImageIcon("C:\\Users\\Gazebo\\Documents\\NetBeansProjects\\TCC POO Sistema Mac Donalds\\Background.png")); // NOI18N
        jLabel8.setMaximumSize(new java.awt.Dimension(500, 500));
        getContentPane().add(jLabel8);
        jLabel8.setBounds(520, 0, 260, 160);

        jLabel9.setIcon(new javax.swing.ImageIcon("C:\\Users\\Gazebo\\Documents\\NetBeansProjects\\TCC POO Sistema Mac Donalds\\Background.png")); // NOI18N
        jLabel9.setMaximumSize(new java.awt.Dimension(500, 500));
        getContentPane().add(jLabel9);
        jLabel9.setBounds(0, 160, 260, 160);

        jLabel10.setIcon(new javax.swing.ImageIcon("C:\\Users\\Gazebo\\Documents\\NetBeansProjects\\TCC POO Sistema Mac Donalds\\Background.png")); // NOI18N
        jLabel10.setMaximumSize(new java.awt.Dimension(500, 500));
        getContentPane().add(jLabel10);
        jLabel10.setBounds(250, 160, 260, 160);

        jLabel11.setIcon(new javax.swing.ImageIcon("C:\\Users\\Gazebo\\Documents\\NetBeansProjects\\TCC POO Sistema Mac Donalds\\Background.png")); // NOI18N
        jLabel11.setMaximumSize(new java.awt.Dimension(500, 500));
        getContentPane().add(jLabel11);
        jLabel11.setBounds(510, 160, 260, 160);

        jLabel12.setIcon(new javax.swing.ImageIcon("C:\\Users\\Gazebo\\Documents\\NetBeansProjects\\TCC POO Sistema Mac Donalds\\Background.png")); // NOI18N
        jLabel12.setMaximumSize(new java.awt.Dimension(500, 500));
        getContentPane().add(jLabel12);
        jLabel12.setBounds(510, 320, 260, 160);

        jLabel13.setIcon(new javax.swing.ImageIcon("C:\\Users\\Gazebo\\Documents\\NetBeansProjects\\TCC POO Sistema Mac Donalds\\Background.png")); // NOI18N
        jLabel13.setMaximumSize(new java.awt.Dimension(500, 500));
        getContentPane().add(jLabel13);
        jLabel13.setBounds(250, 320, 260, 160);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnQuarteiraoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuarteiraoActionPerformed
        // TODO add your handling code here:
        new PersonalizacaoQuarteirao().setVisible(true);
        dispose();
    }//GEN-LAST:event_btnQuarteiraoActionPerformed

    private void btnBigMacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBigMacActionPerformed
        // TODO add your handling code here:
        new PersonalizacaoBigMac().setVisible(true);
        dispose();
    }//GEN-LAST:event_btnBigMacActionPerformed

    private void btnCheeseburgerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCheeseburgerActionPerformed
        // TODO add your handling code here:
        new PersonalizacaoCheeseburger().setVisible(true);
        dispose();
    }//GEN-LAST:event_btnCheeseburgerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaInicial().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBigMac;
    private javax.swing.JButton btnCheeseburger;
    private javax.swing.JButton btnQuarteirao;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
